export const actions = {
    GET_PRODUCTS: "GET_PRODUCTS",
    SAVE_PRODUCT: "SAVE_PRODUCT",
    DELETE_PRODUCTS: "DELETE_PRODUCTS"
};

export const mutations = {
    SET_PRODUCTS: "SET_PRODUCTS"
    // ADD_PRODUCT: "ADD_PRODUCT",
    // UPDATE_PRODUCT: "UPDATE_PRODUCT",
    // DELETE_PRODUCTS: "DELETE_PRODUCTS"
};
