export const actions = {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT"
};

export const mutations = {
    SET_DRAWER: "SET_DRAWER",
    TOGGLE_DRAWER: "TOGGLE_DRAWER",
    START_LOADING: "START_LOADING",
    STOP_LOADING: "STOP_LOADING",
    SET_ERROR: "SET_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR",
    SET_MESSAGE: "SET_MESSAGE",
    CLEAR_MESSAGE: "CLEAR_MESSAGE",
    SET_AUTH: "SET_AUTH",
    CLEAR_AUTH: "CLEAR_AUTH"
};
